/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-29 08:19:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 
if (session.getAttribute("email") == null) {
    response.sendRedirect("log.jsp");
}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Admin Dashboard</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/UprofileStyle.css\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container light-style flex-grow-1 container-p-y\">\n");
      out.write("    <h4 class=\"font-weight-bold py-3 mb-4\">Admin Dashboard</h4>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <nav id=\"sidebar\" class=\"col-md-3 pt-0\">\n");
      out.write("                <div class=\"list-group list-group-flush account-settings-links\">\n");
      out.write("                    <a class=\"list-group-item list-group-item-action active\" data-toggle=\"list\" href=\"#products\">Products</a>\n");
      out.write("                    <a class=\"list-group-item list-group-item-action\" data-toggle=\"list\" href=\"#add-product\">Add Product</a>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"col-md-9\">\n");
      out.write("                <div class=\"tab-content\">\n");
      out.write("                    <!-- Products Tab -->\n");
      out.write("                    <div class=\"tab-pane fade active show\" id=\"products\">\n");
      out.write("                        <h4 class=\"font-weight-bold py-3 mb-4\">Product Management</h4>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <!-- Search bar with search icon -->\n");
      out.write("                            <form method=\"post\" action=\"\">\n");
      out.write("                                <div class=\"input-group\">\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" placeholder=\"Search by Product ID\" name=\"searchProductID\">\n");
      out.write("                                    <div class=\"input-group-append\">\n");
      out.write("                                        <button class=\"btn btn-primary\" type=\"submit\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Product table with remove button for each row -->\n");
      out.write("                        <table class=\"table table-striped\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Product ID</th>\n");
      out.write("                                    <th>Name</th>\n");
      out.write("                                    <th>Description</th>\n");
      out.write("                                    <th>Price</th>\n");
      out.write("                                    <th>Image Location</th>\n");
      out.write("                                    <th>Remove</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                ");

                                    // Database connection parameters
                                    String url = "jdbc:oracle:thin:@localhost:1521:xe";
                                    String user = "jdbc";
                                    String password = "apple";

                                    Connection connection = null;

                                    try {
                                        Class.forName("oracle.jdbc.driver.OracleDriver");
                                        connection = DriverManager.getConnection(url, user, password);

                                        String searchProductID = request.getParameter("searchProductID");

                                        // Fetch products from the database based on the searchProductID
                                        String query = "SELECT * FROM Product";
                                        if (searchProductID != null && !searchProductID.isEmpty()) {
                                            query += " WHERE ProductID = ?";
                                        }
                                        
                                        PreparedStatement statement = connection.prepareStatement(query);
                                        if (searchProductID != null && !searchProductID.isEmpty()) {
                                            statement.setInt(1, Integer.parseInt(searchProductID));
                                        }

                                        ResultSet rs = statement.executeQuery();

                                        while (rs.next()) {
                                
      out.write("\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>");
      out.print( rs.getInt("ProductID") );
      out.write("</td>\n");
      out.write("                                    <td>");
      out.print( rs.getString("Name") );
      out.write("</td>\n");
      out.write("                                    <td>");
      out.print( rs.getString("Description") );
      out.write("</td>\n");
      out.write("                                    <td>");
      out.print( rs.getBigDecimal("Price") );
      out.write("</td>\n");
      out.write("                                    <td>");
      out.print( rs.getString("ImageLocation") );
      out.write("</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <form method=\"post\" action=\"RemoveProduct\">\n");
      out.write("                                            <input type=\"hidden\" name=\"productID\" value=\"");
      out.print( rs.getInt("ProductID") );
      out.write("\">\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-danger\">Remove</button>\n");
      out.write("                                        </form>\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                ");

                                    }
                                } catch (Exception e) {
                                    e.printStackTrace();
                                } finally {
                                    if (connection != null) {
                                        connection.close();
                                    }
                                }
                                
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Add Product Tab -->\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"add-product\">\n");
      out.write("                        <!-- Form for adding a new product -->\n");
      out.write("                        <form method=\"post\" action=\"AddProductServlet\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"form-label\">Name</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"name\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"form-label\">Description</label>\n");
      out.write("                                <textarea class=\"form-control\" name=\"description\"></textarea>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"form-label\">Price</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"price\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"form-label\">Image Location</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"imageLocation\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"text-right mt-3\">\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">Add Product</button>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Logout button -->\n");
      out.write("        <div class=\"text-right mt-3\">\n");
      out.write("            <form method=\"post\" action=\"Logout\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-danger\">Logout</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Include necessary JavaScript libraries -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
