/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-30 07:39:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class book_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write(' ');
 
if (session.getAttribute("email") == null) {
    response.sendRedirect("log.jsp");
}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <!-- Basic -->\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("  <!-- Mobile Metas -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("  <!-- Site Metas -->\n");
      out.write("  <meta name=\"keywords\" content=\"\" />\n");
      out.write("  <meta name=\"description\" content=\"\" />\n");
      out.write("  <meta name=\"author\" content=\"\" />\n");
      out.write("  <link rel=\"shortcut icon\" href=\"images/favicon.png\" type=\"\">\n");
      out.write("\n");
      out.write("  <title> SG </title>\n");
      out.write("\n");
      out.write("  <!-- bootstrap core css -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\" />\n");
      out.write("\n");
      out.write("  <!--owl slider stylesheet -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" />\n");
      out.write("  <!-- nice select  -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css\" integrity=\"sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==\" crossorigin=\"anonymous\" />\n");
      out.write("  <!-- font awesome style -->\n");
      out.write("  <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\" />\n");
      out.write("  <!-- responsive style -->\n");
      out.write("  <link href=\"css/responsive.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"sub_page\">\n");
      out.write("\n");
      out.write("  <div class=\"hero_area\">\n");
      out.write("    <div class=\"bg-box\">\n");
      out.write("      <img src=\"images/hero-bg.jpg\" alt=\"\">\n");
      out.write("    </div>\n");
      out.write("    <!-- header section strats -->\n");
      out.write("    <header class=\"header_section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <nav class=\"navbar navbar-expand-lg custom_nav-container \">\n");
      out.write("          <a class=\"navbar-brand\" href=\"index.jsp\">\n");
      out.write("            <span>\n");
      out.write("              SG\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"\"> </span>\n");
      out.write("          </button>\n");
      out.write("\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("            <ul class=\"navbar-nav  mx-auto \">\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"index.jsp\">Home </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"menu.html\">Menu</a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"about.html\">About</a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item active\">\n");
      out.write("                <a class=\"nav-link\" href=\"book.jsp\">Book Table <span class=\"sr-only\">(current)</span> </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("  <a class=\"nav-link\" href=\"MyOrders.jsp\">My Orders</a>\n");
      out.write("</li>\n");
      out.write("              \n");
      out.write("            </ul>\n");
      out.write("            <div class=\"user_option\">\n");
      out.write("              <a href=\"UserProfile.jsp\" class=\"user_link\">\n");
      out.write("                <i class=\"fa fa-user\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"cart_link\" href=\"cart.jsp\">\n");
      out.write("                <svg version=\"1.1\" id=\"Capa_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 456.029 456.029\" style=\"enable-background:new 0 0 456.029 456.029;\" xml:space=\"preserve\">\n");
      out.write("                  <g>\n");
      out.write("                    <g>\n");
      out.write("                      <path d=\"M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248\n");
      out.write("                   c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z\" />\n");
      out.write("                    </g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                    <g>\n");
      out.write("                      <path d=\"M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48\n");
      out.write("                   C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064\n");
      out.write("                   c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4\n");
      out.write("                   C457.728,97.71,450.56,86.958,439.296,84.91z\" />\n");
      out.write("                    </g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                    <g>\n");
      out.write("                      <path d=\"M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296\n");
      out.write("                   c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z\" />\n");
      out.write("                    </g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                  <g>\n");
      out.write("                  </g>\n");
      out.write("                </svg>\n");
      out.write("              </a>\n");
      out.write("              <form class=\"form-inline\">\n");
      out.write("                <a href=\"search.jsp\" class=\"btn my-2 my-sm-0 nav_search-btn\">\n");
      out.write("  <i class=\"fa fa-search\" aria-hidden=\"true\"></i>\n");
      out.write("</a>\n");
      out.write("\n");
      out.write("              </form>\n");
      out.write("              <a href=\"menu.jsp\" class=\"order_online\">\n");
      out.write("                Order Online\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- end header section -->\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- book section -->\n");
      out.write("  <section class=\"book_section layout_padding\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"heading_container\">\n");
      out.write("        <h2>\n");
      out.write("          Book A Table\n");
      out.write("        </h2>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <div class=\"form_container\">\n");
      out.write("<form action=\"ReservationServlet\" method=\"post\">\n");
      out.write("    <div>\n");
      out.write("        <input type=\"text\" class=\"form-control\" placeholder=\"Your Name\" name=\"name\" />\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("        <input type=\"text\" class=\"form-control\" placeholder=\"Phone Number\" name=\"phone\" />\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div>\n");
      out.write("        <select class=\"form-control nice-select wide\" name=\"persons\">\n");
      out.write("            <option value=\"\" disabled selected>\n");
      out.write("                How many persons?\n");
      out.write("            </option>\n");
      out.write("            <option value=\"2\">\n");
      out.write("                2\n");
      out.write("            </option>\n");
      out.write("            <option value=\"3\">\n");
      out.write("                3\n");
      out.write("            </option>\n");
      out.write("            <option value=\"4\">\n");
      out.write("                4\n");
      out.write("            </option>\n");
      out.write("            <option value=\"5\">\n");
      out.write("                5\n");
      out.write("            </option>\n");
      out.write("        </select>\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("        <input type=\"date\" class=\"form-control\" name=\"reservation_date\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"btn_box\">\n");
      out.write("        <button type=\"submit\" name=\"bookATable\">\n");
      out.write("            Book Now\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <div class=\"map_container \">\n");
      out.write("            <div id=\"googleMap\"></div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <!-- end book section -->\n");
      out.write("\n");
      out.write("  <!-- footer section -->\n");
      out.write("  <footer class=\"footer_section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-4 footer-col\">\n");
      out.write("          <div class=\"footer_contact\">\n");
      out.write("            <h4>\n");
      out.write("              Contact Us\n");
      out.write("            </h4>\n");
      out.write("            <div class=\"contact_link_box\">\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\n");
      out.write("                <span>\n");
      out.write("                  Location\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\n");
      out.write("                <span>\n");
      out.write("                  Call +01 1234567890\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\n");
      out.write("                <span>\n");
      out.write("                  demo@gmail.com\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4 footer-col\">\n");
      out.write("          <div class=\"footer_detail\">\n");
      out.write("            <a href=\"\" class=\"footer-logo\">\n");
      out.write("              SG\n");
      out.write("            </a>\n");
      out.write("            <p>\n");
      out.write("              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with\n");
      out.write("            </p>\n");
      out.write("            <div class=\"footer_social\">\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-facebook\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-twitter\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-instagram\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("              <a href=\"\">\n");
      out.write("                <i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4 footer-col\">\n");
      out.write("          <h4>\n");
      out.write("            Opening Hours\n");
      out.write("          </h4>\n");
      out.write("          <p>\n");
      out.write("            Everyday\n");
      out.write("          </p>\n");
      out.write("          <p>\n");
      out.write("            10.00 Am -10.00 Pm\n");
      out.write("          </p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"footer-info\">\n");
      out.write("        <p>\n");
      out.write("          &copy; <span id=\"displayYear\"></span> All Rights Reserved By\n");
      out.write("          <a href=\"https://html.design/\">Free Html Templates</a><br><br>\n");
      out.write("          &copy; <span id=\"displayYear\"></span> Distributed By\n");
      out.write("          <a href=\"https://themewagon.com/\" target=\"_blank\">ThemeWagon</a>\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("  <!-- footer section -->\n");
      out.write("\n");
      out.write("  <!-- jQery -->\n");
      out.write("  <script src=\"js/jquery-3.4.1.min.js\"></script>\n");
      out.write("  <!-- popper js -->\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\">\n");
      out.write("  </script>\n");
      out.write("  <!-- bootstrap js -->\n");
      out.write("  <script src=\"js/bootstrap.js\"></script>\n");
      out.write("  <!-- owl slider -->\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\">\n");
      out.write("  </script>\n");
      out.write("  <!-- isotope js -->\n");
      out.write("  <script src=\"https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js\"></script>\n");
      out.write("  <!-- nice select -->\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js\"></script>\n");
      out.write("  <!-- custom js -->\n");
      out.write("  <script src=\"js/custom.js\"></script>\n");
      out.write("  <!-- Google Map -->\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap\">\n");
      out.write("  </script>\n");
      out.write("  <!-- End Google Map -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
