/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-27 10:49:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 
if (session.getAttribute("email") == null) {
    response.sendRedirect("Login.jsp");
}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>User Profile</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/UprofileStyle.css\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container light-style flex-grow-1 container-p-y\">\n");
      out.write("        <h4 class=\"font-weight-bold py-3 mb-4\">Account settings</h4>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-3 pt-0\">\n");
      out.write("                <div class=\"list-group list-group-flush account-settings-links\">\n");
      out.write("                    <a class=\"list-group-item list-group-item-action active\" data-toggle=\"list\" href=\"#account-general\">General</a>\n");
      out.write("                    <a class=\"list-group-item list-group-item-action\" data-toggle=\"list\" href=\"#account-change-password\">Change Password</a>\n");
      out.write("                    <a class=\"list-group-item list-group-item-action\" data-toggle=\"list\" href=\"#account-delete-account\">Delete Account</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-9\">\n");
      out.write("                <div class=\"tab-content\">\n");
      out.write("                    <div class=\"tab-pane fade active show\" id=\"account-general\">\n");
      out.write("                        <div class=\"card\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h5 class=\"card-title\">My Profile</h5>\n");
      out.write("                                <form method=\"post\" action=\"Update\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label class=\"form-label\">Name</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control mb-1\" name=\"name\" value=\"");
      out.print( session.getAttribute("name") );
      out.write("\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label class=\"form-label\">E-mail</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control mb-1\" name=\"email\" value=\"");
      out.print( session.getAttribute("email") );
      out.write("\">\n");
      out.write("                                    <div class=\"alert alert-warning mt-3\">\n");
      out.write("                                        Your email is not confirmed. Please check your inbox.<br>\n");
      out.write("                                        <a href=\"javascript:void(0)\">Resend confirmation</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label class=\"form-label\">Phone Number</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"phone_number\" value=\"");
      out.print( session.getAttribute("phone_number") );
      out.write("\">\n");
      out.write("                                </div>\n");
      out.write("                                \n");
      out.write("                                    <div class=\"text-right mt-3\">\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-primary\" name=\"updateProfile\">Update</button>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"account-change-password\">\n");
      out.write("                        <div class=\"card\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h5 class=\"card-title\">Change Password</h5>\n");
      out.write("                                <form method=\"post\" action=\"ChangePassword\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label class=\"form-label\">Current password</label>\n");
      out.write("                                    <input type=\"password\" class=\"form-control\" name = \"current_password\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label class=\"form-label\">New password</label>\n");
      out.write("                                    <input type=\"password\" class=\"form-control\" name = \"new_password\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label class=\"form-label\">Repeat new password</label>\n");
      out.write("                                    <input type=\"password\" class=\"form-control\" name = \"repeat_new_password\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"text-right mt-3\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary\" >Save changes</button>\n");
      out.write("                                </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"account-delete-account\">\n");
      out.write("                        <div class=\"card\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h5 class=\"card-title\">Delete Account</h5>\n");
      out.write("                                <p>Are you sure you want to delete your account? This action cannot be undone.</p>\n");
      out.write("                                <form method=\"post\" action=\"DeleteAccount\">\n");
      out.write("                                    <div class=\"text-right mt-3\">\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-danger\" name=\"deleteAccount\">Delete Account</button>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"text-right mt-3\">\n");
      out.write("            <form method=\"post\" action=\"Logout\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-danger\">Logout</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script data-cfasync=\"false\" src=\"/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.10.2.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
